import { useState } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const switchStyle = {
  "margin": "1%",
  opacity: 0.7,
  "padding-left": "2%",
  "font-size": "16px",

}

export default function Home() {
  const [darkMode, setdarkMode] = useState(false)

  function changeDarkMode() {
    // console.log("swithc" + darkMode)
    setdarkMode(!darkMode)
  }

  function dark_mode() {
    // console.log("dark")
    if (darkMode == true) {
      return "darkmode"
    } else {
      return "lightmode"
    }
  }

  return (
    <div>
      <Head>
        <title>Pick a game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles[dark_mode()]}>
        <div className={styles.heading}>
          <Link href="/ttt">
            <a> tic-tac-toe </a>
          </Link>
          <Link href="/sudoku">
            <a> sudoku </a>
          </Link>
          <Link href="/c4">
            <a> connect 4 </a>
          </Link>
        </div>
        <div className={styles.darkSwitch}>
          <div style={{ "margin-top": "1.1%" }}>
            <label className={styles.switch}>
              <input type="checkbox" onChange={() => { changeDarkMode() }} />
              <span className={styles["slider"] + " " + styles["round"]}></span>
            </label>
          </div>
          <h2 style={switchStyle}> dark mode </h2>
        </div>
      </main>
    </div>
  )
}
